program: train.py
method: random
metric:
  name: total-f1score
  goal: maximize
parameters:
  layer1:
    values: [1024, 512]
  layer2:
    values: [512, 256, 128]
  layer3:
    values: [128, 64, 256]
  dropout_val:
    values: [0.0, 0.2, 0.4, 0.5]
  lr:
    distribution: log_uniform
    max: -9.21 # exp(-9.21) = 1e-4
    min: -13.81 # exp(-13.81) = 1e-6
  epochs:
    value: 30
  path:
    value: './data/wild_images'
  batch_size:
    values: [32, 64, 128]
  activation:
    values: ['tanh', 'ReLU']
  optimizer:
    values: ['adam', 'adamw']
  age_num_targets:
    value: 9
  gender_num:
    value: 2
  race_num:
    value: 5